export const Login = () => <div>Login Page</div>;
export const About = () => <div>About Page</div>;
export const Guide = () => <div>Guide Page</div>;
export const EditMallInfo = () => <div>Edit Mall Info Page</div>;
export const MallInfo = () => <div>Mall Info Page</div>;
export const Detail = () => <div>Detail Page</div>;
export const Search = () => <div>Search Page</div>;
export const Person = () => <div>Person Page</div>;
export const UserInfo = () => <div>User Info Page</div>;
export const UserOrder = () => <div>User Order Page</div>;
export const UpAddress = () => <div>Up Address Page</div>;
export const UpAvatar = () => <div>Up Avatar Page</div>;
export const UpPassWord = () => <div>Up Password Page</div>;
export const GoodsPublish = () => <div>Goods Publish Page</div>;
export const PostPublish = () => <div>Post Publish Page</div>;
export const Im = () => <div>Im Page</div>;
export const AI = () => <div>AI Page</div>;
export const CarbonFootprint = () => <div>Carbon Footprint Page</div>;
